### ISSUE TITLE
Subtest result string

### ISSUE THREAD

**Issue by Altai-man** [tupilabs/tap4j#48]
Hello. Thanks for your work on this library.

As per [this](http://www.node-tap.org/subtests/), a line that describes a subtest result can be either before or after every subtest, but if it's before, some separators(brackets, to be precise) are added.

But tap4j seem to assume first option always. For example,
```
ok 1 - Foo
    ok 1 - st a
    ok 2 - st b
    ok 3 - st c
    1..3
ok 2 - Some subtest
not ok 3 - Bar
```
must be parsed as `test1("Foo"), test2("Some subtest", with three subtests("st a" et cetera), test3("Bar")`.
Instead, it parses like: `test1("Foo", with three subtests), test2("Some subtest"), test3(Bar)`.

**Comment by kinow** [comment]
Hi @Altai-man 

Thanks for reporting the issue.

From what I remember, there was never a formal agreement on subtests. It appeared around the time TAP 13 was being submitted for the IETF as a draft. Some tools implemented it in a way, and others in another different way.

If memory serves me right, there used to be another older page in testanything.org, but it has been archived somewhere after the new site.

Take a look at this Perl doc: https://perldoc.perl.org/Test/More.html

Test::More is much older than node-tap, and probably used the old discussion/spec to implement it. In their example, if I understand correctly, the subtest follows whichever TAP Test Result that precedes it.

It is the first time I see brackets used in TAP. Before I had seen comments with `#` being used as extra information about tests (metadata), as well as the YAMLish syntax. But anything else - including the brackets - would be discarded (which made the TAP syntax a bit trickier to be parsed due to ambiguity).

So not too sure how to proceed. I would like to adapt tap4j to support what node-tap expects, but I think we would have to wait for https://github.com/TestAnything/testanything.github.io/pull/36 to be completed (TAP 14). Hopefully there will be standardization on subtests there.

In the meantime, I would prefer to follow what Perl, C, Shell, PHP, MySQL support (if I remember well the producer/consumers I used in these langs were based on Perl). Hope that makes sense.

**Comment by Altai-man** [comment]
Thanks for you answer, @kinow!

To be honest, I actually want to parse TAP generated by Perl 6, so I took the node link just because it was close enough to refer to.

But, hmm, I may terribly misunderstood something right now, but on Test::More page I see this:
```
  pass("First test");
  subtest 'An example subtest' => sub {
      plan tests => 2;
      pass("This is a subtest");
      pass("So is this");
  };
  pass("Third test");
```
generates:
```
  ok 1 - First test
      # Subtest: An example subtest
      1..2
      ok 1 - This is a subtest
      ok 2 - So is this
  ok 2 - An example subtest
  ok 3 - Third test
```

I.e. first `ok` - is a separate test, then `subtest`, and overall subtest result is a second `ok`, not the opposite. So each subtest result are coming before(!) overall subtest result, not after.

I think there may be some odd misunderstanding between us and it will be great if we could clear up this one.

Perl 6 suite(that implements what `Test::More` does) generates this kind of code too.

**Comment by kinow** [comment]
Oh, I probably misread it. Let me have another look at the Perl example :+1: 

I need to find the old pages I used while writing that part... memory tells me I had to link the subtests with the previous test result. But I rarely trust my memory.

And thanks for pointing it out so politely my mistake :-)

**Comment by kinow** [comment]
Oh well, the link that I sent before was saying the same as you pointed out. My mind was clearly showing me what I wanted :)

I've read some links from Perl, and everything points to the same way; i.e. subtests before. And it even makes sense for me now, as TAP is supposed to be able to be parsed in a Stream, continuously. So the indentation alone should be able to tell the parser it's a subtest... and as the number of test results may be omitted if I recall correctly, the subtests going before would be simpler to parse.

I really can't recall why I implemented it the other way. Will have to have another look later at the git commit history, and try again to find any links to old pages.

But said that, I think it's important to support the Perl behaviour, which would mean supporting node-tap as well :)

Sorry for the confusion @Altai-man 
B

**Comment by Altai-man** [comment]
No problem!

I am happy as long as initial Perl(and so C, MySQL et cetera) behavior will be parsed too at least as a feature with an additional parameter or something like that. 👍

**Comment by Altai-man** [comment]
Closed with the related PR.
