### ISSUE TITLE
tap4j 4.4 missing from maven central

### ISSUE THREAD

**Issue by cburroughs** [tupilabs/tap4j#55]
It appears that for 4.4 only the parent was uploaded.

https://search.maven.org/search?q=tap4j
![missing](https://user-images.githubusercontent.com/24433/52664361-d6045d00-2ed6-11e9-90bd-5f9b8fecfb08.png)

**Comment by kinow** [comment]
Ops. Let me take a look at my local settings and latest changes to see what caused the issue. Will try to update (possibly drop and re-upload) the artefact, though that may not be possible. If that's the case, I will cut 4.4.1, and document in the site and release notes that 4.4. was broken.

Thanks!

**Comment by kinow** [comment]
Funny, just did a `mvn deploy`, and all artefacts were correctly uploaded.

![image](https://user-images.githubusercontent.com/304786/52703436-3680c080-2fe3-11e9-83f3-253755f0dce2.png)

So will go for the easier option, 4.4.1 release is on its way.

**Comment by kinow** [comment]
Looks like 4.4.1 worked, so I will promote the staged repository.

![image](https://user-images.githubusercontent.com/304786/52705294-6e8a0280-2fe7-11e9-8eaf-46581ae8a3d8.png)

**Comment by kinow** [comment]
Now the artefacts were uploaded, with a `sha1` and `md5`, but it failed to release due missing `asc` files... possibly related to https://issues.sonatype.org/browse/OSSRH-40778 :disappointed:

**Comment by kinow** [comment]
Well, looks like it worked after adding the nexus staging maven plugin. Though as this is the first time I released any component this way, there are chances of another mess-up. Mind looking if you can use the 4.4.1 artefacts in a few hours @cburroughs, please? If so feel free to close this issue. Otherwise I feel like I might end up escalating this to Sonatype OSS suppor team.

Cheers

**Comment by cburroughs** [comment]
I see 4.4.1 now, thanks!
